Добавлена модель Контент и админка
hackathon-ambassadors-yandex-pr/ambassadors_backend pull request #11
Opened 2024-03-04 19:47 UTC by MrKlejton

2024-03-04 21:34 UTC, NotMainCode requested changes

2024-03-04 21:34 UTC, NotMainCode commented on apps/content/choice_classes.py
> +NEW = "New", "Новый"
Добавить вариант:
TBC = "TBC", "Уточняется"

2024-03-04 21:34 UTC, NotMainCode commented on apps/content/models.py
> +        null=False,
это значения по умолчанию - удалить строки 12 и 13, а также во всех других случаях этих параметров со значением False

2024-03-04 21:34 UTC, NotMainCode commented on apps/content/models.py
> +    first_and_last_name = models.CharField(
переименовать в `incorrect_full_name`

2024-03-04 21:34 UTC, NotMainCode commented on apps/content/models.py
> +    telegram_link = models.CharField(
переименовать в `incorrect_telegram_link`

2024-03-04 21:34 UTC, NotMainCode commented on apps/content/admin.py
> +        "uploaded_at", "user_comment", "social_network_id",
добавить все остальные поля модели Content

2024-03-04 21:34 UTC, NotMainCode commented on apps/content/models.py
> +    ambassador = models.ForeignKey(
исправить имя файла на `content`

2024-03-04 21:34 UTC, NotMainCode commented on apps/content/models.py
> +        null=True,
удалить, это поле обязательное в таблице ContentFile
связь на скрине означает, что не каждая запись в таблице Content имеет связь с записями в таблице ContentFile (амбассадор может отправить форму контента без прикрепленных файлов контента)
![image](https://github.com/hackathon-ambassadors-yandex-pr/ambassadors_backend/assets/106552134/30b3b2ce-c910-4ce5-9071-7a6896952f84)

2024-03-04 21:34 UTC, NotMainCode commented on apps/content/models.py
> +        default=False
добавить `verbose_name`  - контент в рамках Гайда начинающего амбассадора

2024-03-04 21:34 UTC, NotMainCode commented on apps/content/models.py
> +        verbose_name="название социальной сети",
добавить параметр `unique=True`

2024-03-05 10:19 UTC, hutji commented on apps/content/models.py
> +    first_and_last_name = models.CharField(
@NotMainCode incorrect_full_name = некорректное имя?

2024-03-05 14:55 UTC, NotMainCode commented on apps/content/models.py
> +    first_and_last_name = models.CharField(
да, это поле в котором будет сохранены имя и фамилия из полученной формы Контент амбассадора если в БД не найден амбассадор с такими именем и фамилией

2024-03-06 13:51 UTC, NotMainCode commented on apps/content/models.py
> +        null=True,
моя ошибка - `null=True` нужно оставить

2024-03-06 15:33 UTC, NotMainCode approved these changes

2024-03-06 18:03 UTC, SabjBrus approved these changes

2024-03-06 18:08 UTC, hutji approved these changes

2024-03-06 19:39 UTC, merged