Feat/structure and precommit
hackathon-ambassadors-yandex-pr/ambassadors_backend pull request #5
Opened 2024-02-23 07:29 UTC by hutji

-Организовал структуру проекта, разбил на приложения. Тут прошу посмотреть и дать фидбэк.
-В settings.py разделил INSTALLED_APPS на DJANGO_APPS, LOCAL_APPS, THIRD_PARTY_APPS
-Настроил прекоммит с isort, black, flake8

2024-02-23 18:49 UTC, SabjBrus approved these changes
pip freeze зависимости, остальное косметика

2024-02-23 18:49 UTC, SabjBrus commented on requirements.txt
Не хватает зависимостей для запуска

2024-02-23 18:49 UTC, SabjBrus commented on backend/config/settings.py
> +"""
Предлагаю удалить дефолтные докстринги джанги

2024-02-23 18:49 UTC, SabjBrus commented on backend/config/settings.py
> +# Build paths inside the project like this: BASE_DIR / 'subdir'.
И комменты тоже

2024-02-23 18:49 UTC, SabjBrus commented on backend/apps/ambassadors/views.py
Нужны ли нам views.py в приложениях, вроде все вью будут в api

2024-02-23 18:49 UTC, SabjBrus commented on backend/config/settings.py
> +INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS + THIRD_PARTY_APPS
Если есть такая практика, то выглядит интересно

2024-02-23 18:49 UTC, SabjBrus commented on backend/config/settings.py
> +SECRET_KEY = "django-insecure-76z!c&(nf%2135b(+kczx530x8t2kt$!ra-8-j*)qks@y8*vhx"
Хорошей практикой считается прятать такие вещи в .env (и не хранить в репозитории), а в репозитории оставить .env.example с примером переменных окружения

2024-02-23 18:49 UTC, SabjBrus commented on backend/config/settings.py
> +# DATABASES = {
БД по дефолту закомментирована?

2024-02-23 18:49 UTC, SabjBrus commented on setup.cfg
> +ignore = E501, W503, E265, F811, PT001, D, W504, W292
Может в столбец для читаемости?

2024-02-23 18:49 UTC, SabjBrus commented on setup.cfg
> +exclude = *.pyi,apps/ambassadors/migrations,apps/users/migrations,apps/analytics/migrations,apps/api/migrations,apps/content/migrations,apps/merch/migrations
И это тоже.
*/migrations/ - вроде можно указать и не перечислять всё приложения

2024-02-24 07:50 UTC, NotMainCode requested changes
Сформировать файл requirements.txt.
Дополнить .gitignore согласно рекомендации [JetBrains](https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore) (см. в файле gitignore)
Сформировать файлы .env и .env.sample согласно комментариям в коде.
Папка backend нужна в случае монорепозитория, предлагаю без неё - навигация по проекту будет легче.

2024-02-24 07:50 UTC, NotMainCode commented on backend/config/settings.py
> +# DATABASES = {
Не должно быть закомментированного кода.
Задать настройки БД PostgreSQL (спрятать в .env), установить [Psycopg 3](https://www.psycopg.org/install/)  `pip install psycopg[binary]`.
```
DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.getenv("POSTGRES_DB", "postgres"),
        "USER": os.getenv("POSTGRES_USER", "postgres"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "postgres"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}
```

2024-02-24 07:50 UTC, NotMainCode commented on backend/config/settings.py
> +"""
Удалить докстринг и стандартные комментарии Django

2024-02-24 07:50 UTC, NotMainCode commented on backend/config/settings.py
> +STATIC_URL = "static/"
Задать настройки статики и медиа
```
STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
```

2024-02-24 07:50 UTC, NotMainCode commented on setup.cfg
> +exclude = *.pyi,apps/ambassadors/migrations,apps/users/migrations,apps/analytics/migrations,apps/api/migrations,apps/content/migrations,apps/merch/migrations
более кратко и добавить другие файлы/папки:
```
exclude =
  __init__.py,
  __pycache__,
  apps.py,
  manage.py,
  .git/,
  env/,
  venv/,
  */migrations/
```
добавить настройки для isort:
```
[isort]
profile = black
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
```

2024-02-24 07:50 UTC, NotMainCode commented on backend/config/settings.py
> +DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
Установить DRF и добавить настройки:
```
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}
```

2024-02-24 07:50 UTC, NotMainCode commented on backend/config/settings.py
> +SECRET_KEY = "django-insecure-76z!c&(nf%2135b(+kczx530x8t2kt$!ra-8-j*)qks@y8*vhx"
Спрятать в env:
```
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-76z!c&(nf%2135b(+kczx530x8t2kt$!ra-8-j*)qks@y8*vhx",
)
```

2024-02-24 07:57 UTC, hutji commented on requirements.txt
@SabjBrus Оп! забыл

2024-02-24 07:58 UTC, hutji commented on backend/apps/ambassadors/views.py
@SabjBrus @NotMainCode Исправлю

2024-02-24 07:59 UTC, hutji commented on backend/config/settings.py
> +SECRET_KEY = "django-insecure-76z!c&(nf%2135b(+kczx530x8t2kt$!ra-8-j*)qks@y8*vhx"
@SabjBrus Абсолютли согласен. Тоже еще не притрагивался.

2024-02-24 08:01 UTC, hutji commented on setup.cfg
> +exclude = *.pyi,apps/ambassadors/migrations,apps/users/migrations,apps/analytics/migrations,apps/api/migrations,apps/content/migrations,apps/merch/migrations
> И это тоже. */migrations/ - вроде можно указать и не перечислять всё приложения

Точно. Спасибо

2024-02-24 09:12 UTC, hutji commented on backend/config/settings.py
> +    "apps.analytics",
@NotMainCode Посмотрел про гитигнор, не пойму что там за файлы указаны.

2024-02-24 09:51 UTC, merged

2024-02-24 09:56 UTC, NotMainCode requested changes

2024-02-24 09:56 UTC, NotMainCode commented on config/settings.py
> -STATIC_URL = "static/"
эту строку нужно оставить, иначе как будут работать ссылки на файлы статики

2024-02-24 09:56 UTC, NotMainCode commented on config/settings.py
добавить `load_dotenv()`
https://pypi.org/project/python-dotenv/

2024-02-24 10:42 UTC, hutji commented on config/settings.py
> -STATIC_URL = "static/"
Не заметил как убрал