Feat/ambassadors models
hackathon-ambassadors-yandex-pr/ambassadors_backend pull request #7
Opened 2024-02-28 14:16 UTC by SabjBrus

Добавлена первая версия моделей и админки приложения ambassadors.
Модел Address, Ambassador, AmbassadorTarget, Program, Promocode, Status, Target согласно последней(закрепленной) версии физической ER модели данных с небольшими корректировками.
Так как от таблицы Activity отказались, пока реализовал через CharField со списком choices
В админке минимальный функционал.

2024-02-28 18:57 UTC, NotMainCode requested changes

2024-02-28 18:57 UTC, NotMainCode commented on apps/ambassadors/admin.py
> +    list_display = ("ambassador", "country", "city", "address", "code", "is_current")
добавить поле id

2024-02-28 18:57 UTC, NotMainCode commented on apps/ambassadors/admin.py
> +    list_display = ("value", "ambassador", "replaced_at", "is_current")
добавить поле id

2024-02-28 18:57 UTC, NotMainCode commented on apps/ambassadors/admin.py
> +class StatusAdmin(admin.ModelAdmin):
задать корректное имя класса

2024-02-28 18:57 UTC, NotMainCode commented on apps/ambassadors/admin.py
> +class StatusAdmin(admin.ModelAdmin):
задать корректное имя класса

2024-02-28 18:57 UTC, NotMainCode commented on apps/ambassadors/admin.py
> +class StatusAdmin(admin.ModelAdmin):
задать корректное имя класса

2024-02-28 18:57 UTC, NotMainCode commented on apps/ambassadors/admin.py
> +class StatusAdmin(admin.ModelAdmin):
задать корректное имя класса

2024-02-28 18:57 UTC, NotMainCode commented on apps/ambassadors/admin.py
> +class StatusAdmin(admin.ModelAdmin):
задать корректное имя класса

2024-02-29 06:10 UTC, hutji commented on apps/ambassadors/migrations/0001_initial.py
> +class Migration(migrations.Migration):
Предлагаю добавлять докстринги с неймингом ко всем классам

2024-02-29 10:19 UTC, hutji commented on apps/ambassadors/models.py
> +class Status(models.Model):
Предлагаю писать докстринги с неймингом для классов

2024-02-29 10:19 UTC, hutji commented on apps/ambassadors/models.py
> +        verbose_name="Комментарий пользователся",
опечатка в verbose_name

2024-02-29 10:19 UTC, hutji commented on apps/ambassadors/models.py
> +    gender = models.CharField(
может сделать поле gender: ChoiceField? Есть ли смысл?

2024-02-29 10:21 UTC, hutji approved these changes

2024-03-01 08:17 UTC, NotMainCode commented on apps/ambassadors/models.py
> +    shoe_size = models.CharField(
моя ошибка - в форме это поле ввода, нужно оставить как есть

2024-03-01 13:51 UTC, SabjBrus commented
Изменения согласно замечаниям и рекомендациям в ревью

2024-03-01 17:53 UTC, hutji approved these changes

2024-03-01 18:21 UTC, hutji approved these changes
апрув

2024-03-01 21:00 UTC, NotMainCode requested changes

2024-03-01 21:00 UTC, NotMainCode commented on apps/ambassadors/models.py
> +    CLOTHING_SIZE_CHOICES = [
вместо сток 58-76 создать файл `apps/ambassadors/choice_classes.py`, в котором опрделить классы выбора:
```
class ClothingSize(models.TextChoices):
    """Размеры одежды."""

    XS = "XS"
    S = "S"
    M = "M"
    L = "L"
    XL = "XL"


class EducationTarget(models.TextChoices):
    """Цели обучения."""

    NEW_PROFESSION = "New profession", "Получение новой профессии, чтобы сменить работу"
    DEEPEN_KNOWLEDGE = (
        "Deepen knowledge",
        "Углубление имеющихся знаний, чтобы использовать их в текущей работе",
    )
    OTHER = "Other", "Свой вариант"


class Gender(models.TextChoices):
    "Пол."

    MALE = "Male", "М"
    FEMALE = "Female", "Ж"
```
и соответственно использовать. Например, в строке 92:
`choices=Gender.choices`

2024-03-01 21:00 UTC, NotMainCode commented on apps/ambassadors/models.py
>      telegram_login = models.CharField(
полагаю, поля `telegram_login`, `email`, `mobile_phone` и `blog_link` должны быть уникальны - добавить для них `unique=True`

2024-03-03 08:49 UTC, SabjBrus commented
Вынес Choice Classes в отдельный файл. Добавил unique=True к полям telgram_login, mobile_phone, email и blog_link.

2024-03-03 09:20 UTC, NotMainCode approved these changes

2024-03-04 12:13 UTC, merged