added users/model+admin, fixed url, added pillow
hackathon-ambassadors-yandex-pr/ambassadors_backend pull request #8
Opened 2024-02-29 06:40 UTC by hutji

Добавил модель пользователя(наследуется от AbstractBaseUser), админку.
Изменил  юрлы на сохранение аватара пользователя.

2024-02-29 20:10 UTC, NotMainCode requested changes

2024-02-29 20:10 UTC, NotMainCode commented on apps/users/admin.py
> +class UserAdmin(admin.ModelAdmin):
этот класс необходимо наследовать от Django `UserAdmin`
импортировать `from django.contrib.auth.admin import UserAdmin as DjangoUserAdmin` и соответственно использовать

2024-03-01 03:59 UTC, hutji commented on apps/api/v1/urls.py
> +    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
@NotMainCode мы будем хранить urls токенов отдельно, а остальные urls в api?

2024-03-01 04:35 UTC, hutji commented on apps/users/admin.py
> +class UserAdmin(admin.ModelAdmin):
@NotMainCode  DjangoUserAdmin это просто нейминг? Или это прямо модель которая наследуется от UserAdmin

2024-03-01 07:57 UTC, NotMainCode commented on apps/users/admin.py
> +class UserAdmin(admin.ModelAdmin):
`DjangoUserAdmin` это псевдоним Django класса `UserAdmin, чтобы не было кллизии с нашим именем класса `UserAdmin`
импортировать `from django.contrib.auth.admin import UserAdmin as DjangoUserAdmin`
использовать `class UserAdmin(DjangoUserAdmin):`

2024-03-01 08:00 UTC, NotMainCode commented on config/urls.py
> +    path("api/v1/", include("apps.api.v1.urls")),
тут должно быть `path("api/", include("apps.api.urls")),`

2024-03-01 08:04 UTC, NotMainCode commented on apps/api/v1/urls.py
> +    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
по итогу путь для эндпоинта `refresh` будет в файле `apps/api/vi/tokens/urls.py`

2024-03-02 07:57 UTC, NotMainCode requested changes

2024-03-02 07:57 UTC, NotMainCode commented on apps/api/urls.py
> +    path("v1/", include("apps.api.v1.tokens.urls")),
include("apps.api.v1.urls"

2024-03-02 07:57 UTC, NotMainCode commented on apps/api/v1/urls.py
в этом файледолжно быть:
```
urlpatterns = [
    path("tokens/", include("apps.api.v1.tokens.urls")),
    path("users/", include("apps.api.v1.users.urls")),
]
```

2024-03-02 07:57 UTC, NotMainCode commented on apps/api/v1/tokens/urls.py
> +    path("api/v1/users/login/", TokenObtainPairView.as_view(), name="api_token_auth"),
path для этого эндпоинта расположить в файле `api/v1/users/urls.py`:
```
urlpatterns = [
    path("login/", TokenObtainPairView.as_view(), name="login"),
]
```

2024-03-02 07:57 UTC, NotMainCode commented on media/user/avatars/2023-01-05_16.00.56.jpg
удалить файл

2024-03-02 18:32 UTC, NotMainCode approved these changes

2024-03-03 12:01 UTC, SabjBrus approved these changes

2024-03-04 11:15 UTC, merged